name: CI

on: [push, pull_request]

jobs:
  java:
    name: Java ${{ matrix.platform }} ${{ matrix.java }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java: ['11', '17']
        platform: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Run test suite
        run: mvn -B --no-transfer-progress -Dsurefire.useFile=false test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
           name: errdump
           path: |
             yamcs-core/hs_err*
             yamcs-core/target/surefire-reports/*.dump*
             tests/hs_err*
             tests/target/surefire-reports/*.dump*

  javadoc:
    name: Javadoc ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Generate javadoc
        run: mvn -B --no-transfer-progress -DskipTests javadoc:aggregate

  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Set up webapp
        run: cd yamcs-web/src/main/webapp; npm install
      - name: Build webapp
        run: cd yamcs-web/src/main/webapp; npm run build

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Generate protobin
        run: mvn -B --no-transfer-progress -DskipTests compile
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Set up sphinx
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate HTTP API documentation
        run: |
          cd docs/http-api
          make html
      - name: Generate Server Manual
        run: |
          cd docs/server-manual
          make html
