name: Code Quality

on:
  push:
    branches:
      - master

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Scan code
        run: mvn -P coverage -B --no-transfer-progress -Dsurefire.useFile=false -Dsonar.projectKey=yamcs verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
           name: hs_err_pid
           path: yamcs-core/hs_err*
